### ISSUE TITLE
gluon version of graalvm 21.3?

### ISSUE THREAD

**Issue by marinier** [gluonhq/substrate#1036]
Not sure where to ask this question, so I'll try here. Will gluon be releasing their own version of graalvm 21.3 like was done for 21.2? If so, is there an estimate of when? Thank you!

**Comment by marinier** [comment]
Any response?

**Comment by jperedadnr** [comment]
There should be a new release soon, as there were some issues that have been preventing using a newer version. For instance, this issue has been just closed today https://github.com/oracle/graal/issues/3944
Anyway, you can use the official GraalVM build 21.3 (with JDK 11 and 17) or any dev build.

**Comment by marinier** [comment]
Thanks for the update! Can you say more about using the official GraalVM build? I was under the impression from the gluon mobile documentation that the gluon version was needed. Are there additional steps that I have to take to use the official version?

**Comment by jperedadnr** [comment]
While Gluon's build of GraalVM is the recommended version, because it has been tested to work with Gluon Substrate, preventing any possible breaking changes from the official GraalVM releases, you can use the latter (we test it daily), but you might find some issue (for instance on iOS). 

No extra steps needed, just download it and set GRAALVM_HOME.
