### ISSUE TITLE
Inet6Address::cached_scoped_id removed in JDK 11.0.14

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#1102]
See https://bugs.openjdk.java.net/browse/JDK-8216417

The jniconfig-java11.json file includes the method `Inet6Address::cached_scoped_id`, but that can only be applied only until 11.0.13. Based on GraalVM's java version, Substrate will need to remove it, if JDK >= 11.0.14.

**Comment by johanvos** [comment]
The jni config files we have in Substrate define the contract between the java code and the native implementations. If a native field/method is added/removed or its signature is changed, the existing jni configuration will not work anymore. 
Since this is not about public API's, this can happen in any version without warnings. 
The important thing therefore is that Substrate should only be used with a GraalVM version and a version of the static libs (taken from GraalVM for linux/mac and taken from our JDK mobile builds for other platforms) that match 100% with each other and with the jni config files.
