### ISSUE TITLE
Simplify resourceList declaration

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/substrate#311]
Currently, we need to supply the resources to resourceList as a regex pattern:

```
<resourcesList>
    <list>.*\\.mp3$</list>
</resourcesList>
```

This should be simplified so that the users can only specify the type instead of an regex:

```
<resourcesList>
    <list>mp3</list>
</resourcesList>
```

**Comment by tiainen** [comment]
I believe there will still be a need to be able to define more advanced resource inclusion patterns, so we should not simplify the existing resource list. It would be better to be able to specify both:

- a list of regular expression patterns
- a list of file extensions

Instead of having the current `resourcesList` parameter, we split this into two options: `resourcePatterns` and `resourceExtensions`. This also makes it more clear to the user that you are passing either a regular expression pattern or a simple extension pattern.

**Comment by mipastgt** [comment]
Do you really think it is worthwhile to introduce a new list for this sole purpose? IMHO this is more confusing than helpful.

**Comment by tiainen** [comment]
We'll have to see what developers are most likely to include as resources. Whether it will only be files based on extensions or if there is indeed a need for the current implementation based on regular expression patterns. The current functionality is the most flexible, but it requires some knowledge about the specific syntax for including files based solely on extension.

In any case, I believe we definitely need to update the documentation, because it does not talk about the regular expression syntax in any way. In addition, adding a sample that explains how to include resources files by extension would come in handy and may already be sufficient to deal with this issue.

**Comment by jperedadnr** [comment]
It is documented now, and `runagent` also generate a file that adds a way to include or exclude patterns. I'll close this issue (feel free to reopen if needed).
