### ISSUE TITLE
Cannot run application with WebView

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/substrate#515]
An application with a dependency on JavaFX webview can be build by adding the following to the `reflectionList`:

```
<reflectionList>
    <list>javafx.scene.web.WebView</list>
    <list>javafx.scene.web.WebEngine</list>
</reflectionList>
```

However, when I run the application and try to access the WebView, it throws an exception:

```
Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError: no jfxwebkit in java.library.path
```

**Comment by samyc1201** [comment]
Hi is this issued solved? We plan to use JavaFX WebView to load the page.

**Comment by alaa-abu-zidan** [comment]
mvn clean javafx:run runs smoothly and everything works as expected.
mvn client:compile  fails "java.lang.NoClassDefFoundError: javafx/scene/web/WebView"

**Comment by samyc1201** [comment]
@alaa-abu-zidan you should post whole stack trace... and specify your version... I can load basic webview without issue in iOS without declare it in the reflection list, i guess they added it by default in the configuration... but webview features are not completed yet, it doesn't allow to execute java code from webview (and vice versa)...

**Comment by alaa-abu-zidan** [comment]
@samyc1201 I am not trying any advanced things with the Webview, just loading a local html file.
Platform: MacOS Catalina
GraalVM version: 20.2.0
tested on Gloun client plugin version:  0.1.32 and  0.1.31

[Thu Sep 17 10:53:41 CEST 2020][INFO] [SUB] Fatal error:java.lang.NoClassDefFoundError
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:480)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:349)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:537)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB] Caused by: java.lang.NoClassDefFoundError: javafx/scene/web/WebView
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.getDeclaredMethods(Native Method)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredMethods(HotSpotResolvedObjectTypeImpl.java:979)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.jni.access.JNIAccessibleMethod.anyMatchIgnoreReturnType(JNIAccessibleMethod.java:139)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.jni.access.JNIAccessibleMember.findHidingSubclasses(JNIAccessibleMember.java:103)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.jni.access.JNIAccessibleMember.findHidingSubclasses(JNIAccessibleMember.java:110)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.jni.access.JNIAccessibleMember.setHidingSubclasses(JNIAccessibleMember.java:83)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.jni.access.JNIAccessibleMethod.finishBeforeCompilation(JNIAccessibleMethod.java:135)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.jni.access.JNIAccessFeature.beforeCompilation(JNIAccessFeature.java:348)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$2(NativeImageGenerator.java:611)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:611)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB] Caused by: java.lang.ClassNotFoundException: javafx.scene.web.WebView
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB]     ... 18 more
[Thu Sep 17 10:53:42 CEST 2020][INFO] [SUB] Error: Image build request failed with exit status 1

**Comment by samyc1201** [comment]
@alaa-abu-zidan I double checked my sample code, it really doesn't declare webview in the reflection list and it is working which is able to load local html (pdf.js) and pdf file.

What is your Java version? I suggest you point your java home to graalvm, so you will get more consistent result. My JavaFX version is `<javafx.version>14</javafx.version>`, and I got included this on top of `javafx-controls`:

```
<dependency>
		    <groupId>org.openjfx</groupId>
		    <artifactId>javafx-web</artifactId>
		    <version>${javafx.version}</version>
		</dependency>
```

You added your webview in fxml or Java code? If you added in fxml then I guess you probably need to declare it in reflection list as mentioned in the beginning of this post:

```
<reflectionList>
    <list>javafx.scene.web.WebView</list>
    <list>javafx.scene.web.WebEngine</list>
</reflectionList>
```

For my case, I added webview in Java code, so I guess it is auto linked by GraalVM during static compile, so I don't need to declare it in the reflection list.

For last resort, you can try this in `<configuration>` as well:

```
<nativeImageArgs>
	<nativeImageArg>
		--allow-incomplete-classpath
	</nativeImageArg>
</nativeImageArgs>
```

**Comment by jperedadnr** [comment]
WebView is now supported on Mac.

**Comment by Skhmt** [comment]
> WebView is now supported on Mac.

is it supported on windows?

**Comment by jperedadnr** [comment]
No, not yet
See https://docs.gluonhq.com/#_platforms
