### ISSUE TITLE
Launch Javafx Native Image with terminal console

### ISSUE THREAD

**Issue by phamvanthanh** [gluonhq/substrate#661]
Hi 
Javafx native image built with client-maven-plugin version 0.1.27 does not launch or disconnect from the terminal so cannot see the console log.

This does not happen to sample project HelloWorld (no Javafx) of https://github.com/gluonhq/client-samples/tree/master/Maven

**Comment by tiainen** [comment]
When JavaFX has been detected, we indeed use subsystem `windows` instead of `console`, as implemented with #639.

If you want to see your output, you can either turn verbosity on (see https://docs.gluonhq.com/client/#_configuration on how to configure this for the client maven plugin). Another option is to launch the executable from a command prompt and redirect standard out and err to a file:

    target\client\x86_64-windows\hellofx.exe > out.txt 2>&1

Yet another option is to use the java logging framework and log to a file instead of console.
