### ISSUE TITLE
Add support for WebView on Android

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#687]

**Comment by scientificware** [comment]
@jperedadnr What is the status of this issue ?

**Comment by scientificware** [comment]
@jperedadnr I don't understand the Gluon development around WebView.
WebView in android.webkit is quite different from WebView in OpenJFX !
Google still names it android.webkit but it's no more a webkit implementation.
Your clients may not understand why they have compatibility problems. Some webbrowser behaviors are subtil and need specific code.
Do you drop the W.O.R.A. objective ?
May be I miss an season ? :smiley:
What is the problem with the OpenJDK WebKit implementation ?

**Comment by jperedadnr** [comment]
Fixed with #814

@scientificware WebView in OpenJFX is a vey complex feature (and very heavyweight), we spend tons of resources in maintaining it up to date, based on the changes of WebKit. 
On mobile it does make sense to use the native implementations, which will be always up to date. 
In OpenJFX, that has been always the case, so it is not a new Gluon development.

**Comment by scientificware** [comment]
@jperedadnr Thanks a lot for these clarifications. I understand your point of vue but it's really a shame that OpenJFX/WebKit is not supported. If you run WebView as a simple webbrowser, using native or embedded version is equivalent but when you use it as an UI, it's problematic due to behavior differences : DOM access, JavaScript interface, ... .
Thanks for all your investment in this project.
