### ISSUE TITLE
sysroot should get a version

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#917]
When Gluon Substrate downloads the sysroot for e.g. linux-aarch64 from download2.gluonhq.com, there is no version associated with this.

### Expected Behavior
We want different versions, so that new versions of substrate might download new versions of the sysroot.

**Comment by johanvos** [comment]
We already have a new version of sysroot, but in order to distribute it, we should be able to differentiate between version numbers -- e.g. see https://github.com/gluonhq/client-maven-plugin/issues/315

**Comment by johanvos** [comment]
new sysroot is in https://download2.gluonhq.com/substrate/sysroot/aarch64sysroot-20210424.zip
This can be hard-coded in Substrate. Whenever we need to change the sysroot, we create a new one, with the datestamp, and change this in Substrate so that new versions of Substrate use the new sysroot. 
This should not be flexible. In case a developer wants to use his own sysroot, he can easily overwrite the ~/.gluon/sysroot directory.

**Comment by jperedadnr** [comment]
I've added the version string to the sysroot download link. However, this doesn't check if the sysroot currently installed is older than the given version, so unless the developer uninstalls it manually, it won't get updated. 
I'd suggest we do a follow-up issue on this, and include a version reference in the download folder (there is no other way to check it otherwise).

**Comment by johanvos** [comment]
I'll comment on the PR
